config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  namespace :admin do
    resources :users
  end
  resources :tasks do
    collection do
      post :confirm
    end
  end
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings
end

app/models/labeling.rb
class Labeling < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :labelings, dependent: :destroy
  has_many :labels, through: :labelings
  validates :title, presence: true
  validates :content, presence: true
  validates :expired_at, presence: true
  validates :status, presence: true
  enum status: { 未着手: 1, 着手中: 2, 完了: 3 }
  enum priority: { 低: 1, 中: 2, 高: 3 }
  scope :search_title, -> (title) { where("title LIKE ?", "%#{title}%") }
  scope :search_status, -> (status) { where(status: status)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :destroy
  before_destroy :do_not_destroy_last_admin
  before_update :change_admin

  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  private
  def do_not_destroy_last_admin
    if self.admin? && User.where(admin: :true).count < 2
      throw :abort
    end
  end

  def change_admin
    if User.where(admin: true).count == 1 && self.will_save_change_to_admin?(from: true, to: false)
      errors.add :base, "管理者が一人も居ない状態にはできません！"
      throw(:abort)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :if_not_admin
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  PER = 5

  def index
    @users = User.select(:id, :name, :admin).order(created_at: :DESC)
  end

  def show
    @tasks = @user.tasks.order(created_at: :DESC).page(params[:page]).per(PER)

  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end

  def update
    if @user.update(user_params)
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を更新しました"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」を削除しました"
    else
      redirect_to admin_users_path, notice: "ユーザー「#{@user.name}」は削除できません。管理者ユーザは最低1つ必要です。"
    end
  end

  private

  def if_not_admin
    unless current_user && current_user.admin == true
      flash[:notice] = t("管理者以外は管理画面にアクセスできません")
      redirect_to(tasks_path)
    end
  end

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required
  private
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  PER = 5

  def index
    if params[:sort_expired]
      @tasks = current_user.tasks.order(expired_at: :DESC).page(params[:page]).per(PER)
    elsif params[:sort_priority]
      @tasks = current_user.tasks.order(priority: :DESC).page(params[:page]).per(PER)
    elsif params[:search]
      if params[:search_title].present? && params[:search_status].present?
        @tasks = current_user.tasks.search_title(params[:search_title]).search_status(params[:search_status]).page(params[:page]).per(PER)
      elsif params[:search_title].present?
        @tasks = current_user.tasks.search_title(params[:search_title]).page(params[:page]).per(PER)
      elsif params[:search_status].present?
        @tasks = current_user.tasks.search_status(params[:search_status]).page(params[:page]).per(PER)
      elsif params[:label_id].present?
        @tasks = Task.joins(:labels).where(labels: { id: params[:label_id] }).page(params[:page]).per(PER)
      else
        @tasks = current_user.tasks.order(created_at: :DESC).page(params[:page]).per(PER)
      end
    else
      @tasks = current_user.tasks.order(created_at: :DESC).page(params[:page]).per(PER)
    end
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = Task.create(task_params)
    @task = current_user.tasks.build(task_params)
    if params[:back]
      render :new
    else
      if @task.save
        redirect_to tasks_path, notice: "タスクを新規登録しました"
      else
        render :new
      end
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスクを編集しました"
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "タスクを削除しました"
  end

  private
  def set_task
    @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :content, :expired_at, :status, :priority, { label_ids: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]

  def new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    if @current_user.id != @user.id
      redirect_to tasks_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<h3>【管理】</h3>

<h1>サインアップ</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.label :admin, "管理者権限" %>
  <%= f.radio_button :admin, "true", for: "true" %>あり
  <%= f.radio_button :admin, "false", for: "false" %>なし
  <%#= f.submit "アカウント作成" %>

  <div class="actions">
    <% if controller.action_name == "new" %>
      <%= f.submit 'アカウント作成' %>
    <% else controller.action_name == "edit" %>
      <%= f.submit 'アカウント更新' %>
    <% end %>
  </div>

<% end %>

app/views/admin/users/edit.html.erb
<h2>アカウント編集</h2>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h3>【管理】</h3>
<h3>ユーザーの一覧</h3>

<%= link_to 'ユーザー新規登録', new_admin_user_path %>

<table class="table">
  <thead>
    <tr>
      <th>ユーザーID</th>
      <th>ユーザー名</th>
      <th>タスク数</th>
      <th>管理者権限</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="user_list"><%= user.id %></td>
        <td class="user_list"><%= user.name %></td>
        <td class="user_list"><%= user.tasks.count %></td>
        <td class="user_list"><%= user.admin %></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to "詳細", admin_user_path(user.id) %></button></td>
        <td><button type="button" class="btn btn-outline-success"><%= link_to "編集", edit_admin_user_path(user.id) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to "削除", admin_user_path(user.id), method: :delete, data: { confirm: "本当に削除しますか？" } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'タスク一覧へもどる', tasks_path %>

app/views/admin/users/new.html.erb
<h2>アカウント作成</h2>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h3>【管理】</h3>
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<table class="table">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th>終了期限</th>
      <th>ステータス</th>
      <th>優先度</th>
      <th>ユーザ名</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_list"><%= task.title %></td>
        <td class="task_list"><%= task.content %></td>
        <td class="task_list"><%= task.expired_at %></td>
        <td class="task_list"><%= task.status %></td>
        <td class="task_list"><%= task.priority %></td>
        <td class="task_list"><%= task.user.name %></td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to "詳細", task_path(task.id) %></button></td>
        <td><button type="button" class="btn btn-outline-success"><%= link_to "編集", edit_task_path(task.id) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to "削除", task, method: :delete, data: { confirm: "本当に削除しますか？" } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @tasks, theme: 'twitter-bootstrap-4'%>

<%= link_to '管理画面へもどる', admin_users_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EveryleafTraining</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- 
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    -->
    <!-- Bootstrap CSS -->
    <!-- 
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    -->
    </head>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!-- 
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    -->
  <body>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <% if current_user.admin? %>
        <%= link_to "管理画面", admin_users_path %>
      <% end %>
      <%= link_to "プロフィール", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "サインアップ", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: @task, local: true) do |form| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h4><%= @task.errors.count %>件のエラーがあります。</h4>
      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="title_field">
    <%= form.label :title, "タスク名" %>
    <%= form.text_field :title %>
  </div>

  <div class="content_field">
    <%= form.label :content, "タスク詳細" %>
    <%= form.text_area :content %>
  </div>

  <div class="expired_at_field">
    <%= form.label :expired_at, "終了期限" %>
    <%= form.date_field :expired_at %>
  </div>

  <div class="status_field">
    <%= form.label :status, "ステータス" %>
    <%= form.select :status, Task.statuses.keys, {include_blank: "選択してください"} %>
  </div>

  <div class="priority_field">
    <%= form.label :priority, "優先度" %>
    <%= form.select :priority, Task.priorities.keys, {include_blank: "選択してください"} %>
  </div>

  <div class="lafel_field">
    <%= form.label :label, "ラベル" %>
    <p><%= form.collection_check_boxes(:label_ids, Label.all, :id, :label_name) %></p>
  </div>

  <div class="actions">
    <% if controller.action_name == "new" %>
      <%= form.submit '登録する' %>
    <% else controller.action_name == "edit" %>
      <%= form.submit '更新する' %>
    <% end %>
  </div>

<% end %>

app/views/tasks/edit.html.erb
<h2>タスク編集</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<br>

<div class="search_box" >
  <%= form_with(model: @task, method: :get, local: true) do |form| %>
    <%= form.label :search_title, 'タスク名' %>
    <%= form.text_field :search_title %>

    <%= form.label :search_status, 'ステータス名' %>
    <%= form.select :search_status, Task.statuses.keys, {include_blank: "選択してください"} %>

    <%= form.label :label_id, 'ラベル名' %>
    <%= form.select("label_id", Label.pluck(:label_name, :id), { include_blank: true }) %>

    <%= form.submit '検索', name: 'search' %>
  <% end %>
</div>

<h4>
  <button type="button" class="btn btn-primary">
    <%= link_to "新規登録", new_task_path, :style=>"color:white;" %>
  </button>
</h4>

<table class="table">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>タスク詳細</th>
      <th class="sort_expired"><%= link_to "終了期限", tasks_path(sort_expired: "true") %></th>
      <th>ステータス</th>
      <th class="sort_priority"><%= link_to "優先度", tasks_path(sort_priority: "true") %></th>
      <th>ユーザー名</th>
      <th>ラベル</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td class="task_list"><%= task.title %></td>
        <td class="task_list"><%= task.content %></td>
        <td class="task_list"><%= task.expired_at %></td>
        <td class="task_list"><%= task.status %></td>
        <td class="task_list"><%= task.priority %></td>
        <td class="task_list"><%= task.user.name %></td>
        <td class="task_list">
          <% task.labels.each do |label| %>
            <p class="label label-info"><%= label.label_name %></p>
          <% end %>
        </td>
        <td><button type="button" class="btn btn-outline-primary"><%= link_to "詳細", task_path(task.id) %></button></td>
        <td><button type="button" class="btn btn-outline-success"><%= link_to "編集", edit_task_path(task.id) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to "削除", task, method: :delete, data: { confirm: "本当に削除しますか？" } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <%= paginate @tasks, theme: 'twitter-bootstrap-4'%>

app/views/tasks/new.html.erb
<h2>タスク新規登録</h2>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h3>タスク詳細</h3>

<p>
  <strong>タスク名</strong>
  <%= @task.title %>
</p>

<p>
  <strong>タスク詳細</strong>
  <%= @task.content %>
</p>

<p>
  <strong>終了期限</strong>
  <%= @task.expired_at %>
</p>

<p>
  <strong>ステータス</strong>
  <%= @task.status %>
</p>

<p>
  <strong>優先度</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>ラベル</strong>
  <% @task.labels.each do |label| %>
    <h3 class="label label-info"><%= label.label_name %></h3>
  <% end %>
</p>

<p>
  <strong>ユーザー</strong>
  <%= @task.user.name %>
</p>

<%= link_to '戻る', tasks_path %>

app/views/users/new.html.erb
<h1>サインアップ</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "アカウント作成" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>

<%= link_to 'タスク一覧へもどる', tasks_path %>